### ISSUE TITLE
OBDragDropManager EXC_BAD_ACCESS crash

### ISSUE THREAD

**Issue by hishamabri** [Oblong/OBDragDrop#16]
Hi

Thanks for the great library
I keep getting this error EXC_BAD_ACCESS on this function:

-(BOOL) ovumRecognizerShouldHandleTouch:(UIGestureRecognizer <OBDragDropGestureRecognizer>*)recognizer {
    if (recognizer.state == UIGestureRecognizerStateBegan) {
        id<OBOvumSource> ovumSource = recognizer.ovumSource;
        
        if ([ovumSource respondsToSelector:@selector(shouldCreateOvumFromView:)] && //On this line
            ![ovumSource shouldCreateOvumFromView:recognizer.view])
        {
            // Workaround to cancel the gesture recognizer
            recognizer.enabled = NO;
            recognizer.enabled = YES;
            return NO;
        }
        return YES;
    }
    
    return recognizer.ovum != nil;
}

I am using the gesture recognizer on UITableViewCells.

When the application goes to the background and comes back to the foreground, if I touch one of the cells (most of the time) it will crash the app.
The ovumSource in the gesture recognizer is held with an assign attribute, so they are naturally not strongly holding the object.

My OvumSource object is strongly held by my TableViewController.

Any ideas?

Thanks

**Comment by zaichang** [comment]
Hi there,

Sorry for the belated response. I added a UITableView source in the test project, but wasn't able to reproduce the error you saw.

There's a subtlety with using the drag drop framework on UITableViewCells in case you're not aware, whereby one should take care not to add more than one instance of the drag drop gesture recognizer.

Here's a snippet:
```
- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath
{
  UITableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:kCellIdentifier forIndexPath:indexPath];

  ...

  // Drag drop with long press gesture
  //
  // Be careful with attaching gesture recognizers inside tableView:cellForRowAtIndexPath: as cells
  // get reused. Add a check to prevent multiple gesture recognizers from being added to the same cell.
  // The below check is crude but works; you may need something more specific or elegant.
  if (cell.gestureRecognizers.count == 0) {
    OBDragDropManager *dragDropManager = [OBDragDropManager sharedManager];
    UIGestureRecognizer *recognizer = [dragDropManager createLongPressDragDropGestureRecognizerWithSource:self];
    [cell addGestureRecognizer:recognizer];
  }
}
```

Let me know if that helps.

**Comment by hishamabri** [comment]
Hi there,

sorry for my late reply too.

I have made sure that i don't add extra gesture recognisers, but the issue was still occurring.
I made a little modification on 
@property (nonatomic, assign) id<OBOvumSource> ovumSource;
and made the property weak instead.
That seems to stop the crashing and work OK.
Not sure if that's the correct way of fixing the problem though.

**Comment by zaichang** [comment]
Hey there,

Are you referring to the protocol definition of OBDragDropGestureRecognizer? I do see that we're using retain/assign instead of strong/weak ... the change makes sense since the weak reference would prevent the crashes you're seeing.

I can change it from my end, or if you'd like submit a pull request and I'll merge it.
