### ISSUE TITLE
Offset drag representation

### ISSUE THREAD

**Issue by crispinb** [Oblong/OBDragDrop#18]
What might cause the drag representation to be offset from the touch point, and its movement to be transformed exactly by the orientation angle (ie. 90deg for land right, 180 deg for reversed portrait)?

I found this to happen when trying an initial integration in a project of mine. I couldn't see anything wrong (OBDragDropManager::handleApplicationOrientationChange is being called, & the overlay window transformation looks OK), The demo project checked out from git works fine.

So I tried the simplest test project I could think of: an exact copy of the demo project classes, but set up in a new empty Xcode 7.1 iOS project. This has the issue: offset representation and transformed movement! Literally the only differences from the (working) checked out demo project are what's in the info.plist and pbxproj. I looked through the build settings but couldn't see anything obviously relevant.

I ran out of time to spend on this, so will have a deeper dig next week. Anyone have any obvious clues in the meantime?

[Edit: forgot to mention a crucial point: the issue *only happens on iPads* (simulator & device alike). Both versions of the demo project (checked-out and new-project) are fine on all iPhones]

**Comment by crispinb** [comment]
The problem turned out to be a wrong value returned from  the `[UIWindow convertRect:fromWindow:]` call in my `[createDragRepresentationOfSourceView:inWindow:]` implementation. The sample project and my copy of it, though literally identical at a source level, were returning different values for this call.

Incredibly weirdly this turned out to be caused by the presence of a UILaunchStoryboardName key/value in the Info.plist, found simply by diffs between the github sample project and my own copy sample. I have zero insight into what this key has to do with the frame conversion between the app and overlay windows. But there it is.

**Comment by zaichang** [comment]
I remember something vaguely similar when we were testing the beta releases
of iOS 9, whereby the pan gesture in conjunction with window transformation
was causing coordinate calculations to be wrong. This was fixed by 9.0 GM
the last time I checked.

However, using the test app now I see that the contents themselves seem to
be rotated because of the window rotation and will patch it up.
