### ISSUE TITLE
OBOvum Dropped outside dropzone

### ISSUE THREAD

**Issue by danielcardeenas** [Oblong/OBDragDrop#24]
Is there any way to catch this event?

**Comment by danielcardeenas** [comment]
Found out you can catch this event with method
 `- (void)ovumDragEnded:(OBOvum *)ovum`

**Comment by zaichang** [comment]
Hi Daniel, you're right the OBOvumSource from which the drag and drop action initiated has some lifecycle events you can hook into including and drag and drop which did not complete.

The OBDragDropProtocol.h file has the interfaces and better commentary than README.md (which should probably be updated actually)
https://github.com/Oblong/OBDragDrop/blob/master/Classes/OBDragDropProtocol.h
