### ISSUE TITLE
CocoaPods version

### ISSUE THREAD

**Issue by drdaz** [Oblong/OBDragDrop#29]
Hi there

The version of this awesome thing in CocoaPods is still 1.0.0... looking at the state of things here it's a little behind the times :)

/drdaz

**Comment by zaichang** [comment]
Hi @drdaz I just pushed a new podspec for OBDragDrop (1.0.3). Hope that helps!

Also thanks for your interest / use of our little library. Do you mind sharing in what app you're using it?
